### ISSUE TITLE
[Bug] Permission denied in newer versions

### ISSUE THREAD

**Issue by bbuzz31** [asfadmin/Discovery-asf_search#100]
Download functionality of asf_search seems to have broken in v3.1.2 and later.

I suspect that it's no longer reading credentials in `$HOME/.netrc` as:
1. the URLs can be downloaded manually after logging into EarthData
2. I can start an ASFSession with my credentials and products will download.

MWE
```
import os
import asf_search as asf
## this fails in versions >= 3.1.2 with the error below script
dct_kw = {'platform': 'Sentinel-1', 'processingLevel': 'GUNW_STD', 'relativeOrbit': [124], 'lookDirection': None, 'intersectsWith': None}
scenes = asf.geo_search(**dct_kw)
scene1 = scenes[0]
scene1.download(os.getcwd())


## this works in all versions (obviously with real id/pass)
# session = asf.ASFSession()
# session.auth_with_creds('id', 'pass')
# scene1.download(os.getcwd(), session=session)

```
asf_search.exceptions.ASFAuthenticationError: HTTP 401: HTTP Basic: Access denied.

**Comment by SpicyGarlicAlbacoreRoll** [comment]
@bbuzz31 Thank you for letting us know, we've started looking into this issue!

**Comment by SpicyGarlicAlbacoreRoll** [comment]
netrc authentication is now available again with asf_search V3.2.2, thanks again for opening the issue!

**Comment by bbuzz31** [comment]
Thanks!

**Comment by bbuzz31** [comment]
If you could also update conda-forge it would be great!
