### ISSUE TITLE
[Bug] Differences between search.py in pip install version and github master branch version

### ISSUE THREAD

**Issue by Yuran-Zhao** [asfadmin/Discovery-asf_search#145]
**Describe the bug**
[Line 143 in search/search.py](https://github.com/asfadmin/Discovery-asf_search/blob/8761e2b94ac3f7585723490001795da0cb043f70/asf_search/search/search.py#L143) is commented in the master branch, while it is uncommented in the search.py installed by pip.

**To Reproduce**
1. python3 -m pip install asf_search
2. vim /path/to/asf_search/search/search.py
3. see line 143

**Expected behavior**
The behaviors should be consistent.

**Comment by SpicyGarlicAlbacoreRoll** [comment]
Thank you for bringing this to our attention! Line 143 has been uncommented on the master branch.
