### ISSUE TITLE
IPF Versions for Sentinel-1 SLC

### ISSUE THREAD

**Issue by cmarshak** [asfadmin/Discovery-asf_search#170]
**Is your feature request related to a problem? Please describe.**
Want IPF versions (in CMR) in asf search

**Describe the solution you'd like**
From @asjohnston-asf:

+ Echo10: https://cmr.earthdata.nasa.gov/search/granules.echo10?provider=ASF&granule_ur=S1A_IW_SLC__1SDH_20230208T083928_20230208T083955_047142_05A7F0_0F03-SLC
+ umm-json: https://cmr.earthdata.nasa.gov/search/granules.umm_json?provider=ASF&granule_ur=S1A_IW_SLC__1SDH_20230208T083928_20230208T083955_047142_05A7F0_0F03-SLC

**Additional context**
Two different IPF versions for different dates cannot be used to generate an interferogram.

**Comment by asjohnston-asf** [comment]
Per @glshort , `ASFProduct` search results include the entire `umm` payload retrieved from CMR, so you can access the IPF version if you know the jsonpath to the IPF version in the UMM schema:

```
>>> results = asf_search.product_search('S1A_IW_SLC__1SDH_20230208T083928_20230208T083955_047142_05A7F0_0F03-SLC')
>>> results[0].umm['PGEVersionClass']['PGEVersion']
'003.52'
```
