### ISSUE TITLE
Support searching by TEMPORAL_BASELINE_DAYS attribute for S1 ARIA GUNW products

### ISSUE THREAD

**Issue by asjohnston-asf** [asfadmin/Discovery-asf_search#198]
New S1 ARIA GUNW products will soon include a `TEMPORAL_BASELINE_DAYS` attribute in CMR. @cmarshak is interested in being able to search by this parameter using `asf_search`.

For more context, see https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/issues/136

This applies to the five CMR collections with `ASF_PLATFORM=Sentinel-1 Interferogram (BETA)`; these CMR collection short names:
- SENTINEL-1_INTERFEROGRAMS
- SENTINEL-1_INTERFEROGRAMS_AMPLITUDE
- SENTINEL-1_INTERFEROGRAMS_COHERENCE
- SENTINEL-1_INTERFEROGRAMS_CONNECTED_COMPONENTS
- SENTINEL-1_INTERFEROGRAMS_UNWRAPPED_PHASE

**Comment by cmarshak** [comment]
I would be happy to help if there was some guidance to do this.

**Comment by asjohnston-asf** [comment]
@cmarshak are you interested in exact matches only, e.g. "show me all products with a temporal baseline of 12?" Or do you have a use case for range searches, e.g. "show me all products with a temporal baseline between 12 and 36, inclusive?"

**Comment by cmarshak** [comment]
I think *exact* matches because we want to associate a unique GUNW from:

1. Time range `start-time`
2. Frame number
3. Temporal baseline

**Comment by SpicyGarlicAlbacoreRoll** [comment]
Opened a PR with `temporalBaselineDays` as a searchable keyword, allows searching via temporal baseline, or a list of temporal baselines that match the exact values provided (rather than ranges)

**Comment by cmarshak** [comment]
For reference, on the UAT venue, we should be able to get a unique GUNW from

+ `frame_id =25502`
+ `temporal_baseline_days=12`
+ `start_time` in `2022-02-24` to `2022-02-25`

**Comment by asjohnston-asf** [comment]
FYI, for reference, the equivalent CMR search request for Charlie's criteria would be:
https://cmr.uat.earthdata.nasa.gov/search/granules.umm_json?short_name=SENTINEL-1_INTERFEROGRAMS&temporal=2022-02-24T00:00:00Z,2022-02-25T00:00:00Z&attribute[]=int,FRAME_NUMBER,25502&attribute[]=int,TEMPORAL_BASELINE_DAYS,12

**Comment by cmarshak** [comment]
Please let me know when this can be tested @SpicyGarlicAlbacoreRoll.

**Comment by SpicyGarlicAlbacoreRoll** [comment]
While `asfPlatform` isn't available in asf-search yet, it is possible to get the S1 GUNW products for the time being without it by setting `platform` to SENTINEL1.

using your example parameters, the following examples yields the 5 products for a single unique scene (`S1-GUNW-A-R-164-tops-20220224_20220212-222854-00071W_00047N-PP-6c60-v3_0_0`):

``` python
import asf_search as asf

opts = asf.ASFSearchOptions(host='cmr.uat.earthdata.nasa.gov', platform=asf.SENTINEL1, frame=25502, start=datetime(2022, 2, 24), end=datetime(2022, 2, 25), temporalBaselineDays=[12])
results = asf.search(opts=opts)

for f in results:
    print(f.properties['fileID'])
```

we are still considering whether or not to enable `asfPlatform` as a keyword argument, however if results do need to be narrowed to `ASF_PLATFORM=Sentinel-1 Interferogram (BETA)` products (say `TEMPORAL_BASELINE_DAYS` finds its way to other S1 collection products), either set the `collections` (available in the next release) or the `processingLevel` params like so:

``` python
collections = ['C1225776654-ASF','C1225776655-ASF','C1225776657-ASF','C1225776658-ASF','C1225776659-ASF'] # UAT S1 gunw concept-ids
opts = asf.ASFSearchOptions(host='cmr.uat.earthdata.nasa.gov', frame=25502, collections=collections, platform=asf.SENTINEL1, start=datetime(2022, 2, 24), end=datetime(2022, 2, 25), temporalBaselineDays=[12])
```

``` python
opts = asf.ASFSearchOptions(host='cmr.uat.earthdata.nasa.gov', frame=25502, processingLevel=['GUNW_UNW', 'GUNW_CON', 'GUNW_COH', 'GUNW_AMP', 'GUNW_STD'], platform=asf.SENTINEL1, start=datetime(2022, 2, 24), end=datetime(2022, 2, 25), temporalBaselineDays=[12])
```
Personally I'd recommend the `collection` keyword method once it's made available, since it will dodge the subquery system (less requests to CMR), unlike `processingLevel`.

**Comment by SpicyGarlicAlbacoreRoll** [comment]
This should be available for you to test on the `feature-temporal-baseline-days-search` branch (PR #199 )

**Comment by SpicyGarlicAlbacoreRoll** [comment]
@cmarshak `feature-temporal-baseline-days-search` is ready for you to try out. We likely won't go through with adding the `asfPlatform` keyword in a future release, but I've provided some alternative methods of limiting results to products from `Sentinel-1 Interferogram (BETA)` collections.

**Comment by cmarshak** [comment]
Thanks, @SpicyGarlicAlbacoreRoll - this is what I will use:

```
import asf_search as asf
from datetime import datetime

opts = asf.ASFSearchOptions(host='cmr.uat.earthdata.nasa.gov', 
                            platform=asf.SENTINEL1,
                            processingLevel=asf.constants.GUNW_STD,
                            frame=25502, 
                            start=datetime(2022, 2, 24), 
                            end=datetime(2022, 2, 25), 
                            temporalBaselineDays=[12],
                            )
results = asf.search(opts=opts)

for f in results:
    print(f.properties['fileID'])
```

I used `%%timeit` to check the speed and found:

```
1.01 s ± 75.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

If I want to check about 250k products, is there any way to increase performance? I was going to multithread 5 requests at a time as I was told not to run more than that? Could I thread more?

Let me know your thoughts.

Also, I think the GUNWs are now official NASA products managed in part by @asjohnston-asf - no longer "Beta".

**Comment by SpicyGarlicAlbacoreRoll** [comment]
I will say I haven't tried using asf-search's general search methods with multithreading (that use case to my knowledge remains untested), but I don't believe there's a particular limit on threads while using `search()` beyond what your machine can handle and how many simultaneously connections CMR will tolerate from a single IP address (again, this is untested).

If I were to try, I'd split my threads up by date ranges. Also, Including concept-ids with the `collections` keyword _may_ yield faster results when querying CMR (at least this is behavior we've observed when searching for S1 `granule_ur[]`s with concept-ids in SearchAPI, though this hasn't been benchmarked with other more complex query params).
