### ISSUE TITLE
[Bug] Importing Error

### ISSUE THREAD

**Issue by sreeram-radhakrishnan** [asfadmin/Discovery-asf_search#210]
**Describe the bug**
I tried to install asf-search on linux OpenSuSE 15.4, it was installed perfectly, but while I tried to import it is giving error. I have attached the error msg below. Please let me know how to correct it. My python version is 3.6.15

**Desktop (please complete the following information):**
 - OS : OpenSuSE Leap15.4

![image](https://github.com/asfadmin/Discovery-asf_search/assets/85307395/4b8f6971-f439-4bae-83ad-faa3a12c60f2)
![image](https://github.com/asfadmin/Discovery-asf_search/assets/85307395/52295c05-cf7a-49af-8f27-6097566d9058)

**Comment by Cameronsplaze** [comment]
Thanks for the report @sreeram-radhakrishnan!

Python 3.6 (and just recently 3.7) hit End of Life. Also f-strings were just introduced in 3.6, so I wander if you're hitting a bug there. Are you able to try python3.8+ and see if that fixes it?

Also, what version of asf_search et all are you running? (`python3 -m pip freeze`)

Thanks!
