### ISSUE TITLE
Can't install latest `asf_search` on ARM Mac via conda due to `remotezip`

### ISSUE THREAD

**Issue by scottstanie** [asfadmin/Discovery-asf_search#240]
**Describe the bug**
It looks like the conda package for `remotezip`, despite being a pure python package, is not getting built as a `noarch` conda package: https://anaconda.org/conda-forge/remotezip

This means that on my M1 Mac, I get this error during the `asf_search` install:

```
$ mamba install "asf_search>=6.7"
...
Could not solve for environment specs
Encountered problems while solving:
  - nothing provides remotezip >=0.10.0 needed by asf_search-6.7.0-pyhd8ed1ab_0

```

It seems like somebody could add `remotezip` to the list the conda has for migrating packages to osx-arm, but I can't tell from the [remotezip recipe](https://github.com/conda-forge/remotezip-feedstock/blob/main/recipe/meta.yaml) it wouldn't be built once as a `noarch`.

**Desktop (please complete the following information):**

```
$ mamba info

     active environment : base
    active env location : /Users/staniewi/miniconda3/envs/mapping
            shell level : 2
       user config file : /Users/staniewi/.condarc
 populated config files : /Users/staniewi/.condarc
          conda version : 4.13.0
    conda-build version : 3.23.3
         python version : 3.10.10.final.0
       virtual packages : __osx=13.6.2=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/staniewi/miniconda3/envs/mapping  (writable)
      conda av data dir : /Users/staniewi/miniconda3/envs/mapping/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/staniewi/miniconda3/envs/mapping/pkgs
                          /Users/staniewi/.conda/pkgs
       envs directories : /Users/staniewi/miniconda3/envs/mapping/envs
                          /Users/staniewi/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.13.0 requests/2.28.2 CPython/3.10.10 Darwin/22.6.0 OSX/13.6.2
                UID:GID : 503:20
             netrc file : /Users/staniewi/.netrc
           offline mode : False
```

**Additional context**

Note that I was able to install the `asf_search` via pip into my conda environment, so I don't have any urgent problems.

**Comment by jhkennedy** [comment]
@scottstanie Hmm, `asf_search` should/could be built as a `noarch` package (...wonder if *I* messed that up?). I'll take a look at the [conda-forge recipe](https://github.com/conda-forge/asf_search-feedstock/)

**Comment by jhkennedy** [comment]
Well, yes, this was my fault :facepalm: : 
https://github.com/conda-forge/staged-recipes/pull/14503

There's nothing in `asf_search` that would prevent a `noarch` build, so I've opened https://github.com/conda-forge/asf_search-feedstock/issues/51 and will move it along.

**Comment by jhkennedy** [comment]
@scottstanie remotezip unfortunately can't be built as `noarch` because of this:
https://github.com/gtsystem/python-remotezip/blob/master/setup.py#L19

I'll open a PR upstream and see if we can get that changed to an entry_point.

**Comment by jhkennedy** [comment]
@scottstanie remotezip v0.12.2 is not on PyPI and should be available on conda-forge soon. The conda-forge build is now a `noarch` Python build, so I think you should be able to install `asf_search` on ARM Mac now, and I don't think we need to update anything on the `asf_search` side. Can you take it for a spin and let us know if you encounter any issues?

**Comment by scottstanie** [comment]
looks all good! Thanks for following up


```$ mamba install asf_search

Looking for: ['asf_search']
....

  Package       Version  Build         Channel         Size
─────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────

  + remotezip    0.12.2  pyhd8ed1ab_0  conda-forge     14kB
  + asf_search    6.7.2  pyhd8ed1ab_0  conda-forge     56kB

  Downgrade:
─────────────────────────────────────────────────────────────

  - tenacity      8.2.3  pyhd8ed1ab_0  conda-forge     23kB
  + tenacity      8.2.2  pyhd8ed1ab_0  conda-forge     22kB
  ```
