### ISSUE TITLE
[Bug]Searching the burst stack based on asf_search is much less compared to the ASF site.

### ISSUE THREAD

**Issue by ZGHHGZ** [asfadmin/Discovery-asf_search#244]
Taking 'S1_303069_IW3_20231004T101321_VV_AF9D-BURST' as an example, only 5 images can be searched using python, and 15 images can be searched on the asf website.

![8ade62d29618330b075cd7c6a5f3c96](https://github.com/asfadmin/Discovery-asf_search/assets/88225620/071bd09a-fbb5-4116-9a2c-ba9c955114df)

![68581427d92b29e8521aa527eaced11](https://github.com/asfadmin/Discovery-asf_search/assets/88225620/a0614956-0101-415c-b46f-827bf9ecd948)

**Comment by SpicyGarlicAlbacoreRoll** [comment]
Thank you for filing a bug report!

This issue stems from how Vertex failing to handle null perpendicular values as expected. The BURST products missing from the asf-search based stack are actually missing state vectors in CMR. By default asf-search removes these products from the stack while the SearchAPI keeps them in and assigns a null value to their perpendicular baselines. Consequently, the ASF Data Search website (which depends on SearchAPI) interprets these null perpendicular baseline values as being `0`, whereas they should be marked as non-existent instead.

asf-search will be changed to keep these products with missing state vectors in the stack in the near future with this pull request #248, and we're looking into ways for the website to show which products are missing state vectors in baseline and sbas searches.
