### ISSUE TITLE
[Feature] Harmonize parameters between search() and search_count()

### ISSUE THREAD

**Issue by tylere** [asfadmin/Discovery-asf_search#246]
**Is your feature request related to a problem? Please describe.**
It is often useful to be able to check how many records are available (via `search_count()` before requesting records (via `search()`). However, several parameters available in `search()` are not available in `search_count()`.

**Describe the solution you'd like**
Have the same list of parameters for `search()` and `search_count()`.

In particular, the [Search API Keywords](https://docs.asf.alaska.edu/api/keywords/) says the `dataset` keywords is preferred, but `search_count()` does not accept that keyword.

**Describe alternatives you've considered**
Request a list records via `search()` then calculate the lengths of the list, but that is pretty inefficient.

**Other information**
`asf_search.__version__ == 6.7.2`

**Comment by SpicyGarlicAlbacoreRoll** [comment]
Thank you for filing an issue!

This discrepancy will be addressed with #249

**Comment by SpicyGarlicAlbacoreRoll** [comment]
This issue has been fixed in v6.7.3!
https://github.com/asfadmin/Discovery-asf_search/releases/tag/v6.7.3
