### ISSUE TITLE
[Feature] Document `processingLevel='RTC'`

### ISSUE THREAD

**Issue by tylere** [asfadmin/Discovery-asf_search#247]
**Is your feature request related to a problem? Please describe.**
The [Search API Keywords](https://docs.asf.alaska.edu/api/keywords) page does not document `processingLevel='RTC'` which is used by OPERA RTC-S1.

**Describe the solution you'd like**
Update the keywords page.

**Describe alternatives you've considered**
None.

**Comment by SpicyGarlicAlbacoreRoll** [comment]
Thank you again for filing an issue. Our documentation page is also open source, and the repo can be found on github here for issue reporting:
https://github.com/asfadmin/Discovery-asf-data-search-manual

Tangentially related, there will be OPERA-S1 specific processing level constants added to the asf-search module with this pull request #250

**Comment by ccfleming417** [comment]
Thank you for reporting this issue. The `processingLevel` values have been updated on the [SearchAPI Keywords page](https://docs.asf.alaska.edu/api/keywords/)
