### ISSUE TITLE
No module named 'importlib.metadata ' problem with python 3.6

### ISSUE THREAD

**Issue by alvaroparedesl** [asfadmin/Discovery-asf_search#29]
Hi!

I'm having this problem of no metadata sub-module in importlib, but I do have a importlib_metada module that seems to work fine. I don't know if I'm the only one, but maybe adding something like this could prevent this problem from other users too

```
try:
    from importlib.metadata import PackageNotFoundError, version
except ImportError: # for Python<3.8
    from importlib_metadata import PackageNotFoundError, version
```

I added this to the `asf_search/__init__.py `,  `asf_search/search/search.py` and `asf_search/download/download.py` modules and so far it's working well. Could something like that be included in future releases?

**Comment by jhkennedy** [comment]
Thanks for the report @alvaroparedesl ! 

`importlib_metadata` is a "backport" of `importlib.metadata` for python < 3.8, and an alias to `importlib.metadata` otherwise, so we could just use it instead of `importlib.metadata`. 

I've proposed a fix in #30
