### ISSUE TITLE
[Feature] Skip over existing downloads

### ISSUE THREAD

**Issue by bbuzz31** [asfadmin/Discovery-asf_search#65]
Hi all, great work you've done here.

I recently found that when I try and download an existing dataset (an ARIA product in this case) the code errors out:
`asf_search.exceptions.ASFDownloadError: File already exists: ~/products/S1-GUNW-A-R-004-tops-20210805_20210712-230647-37654N_35777N-PP-8a73-v2_0_4.nc`

Previously the bulk downloader would just skip and continue, which is preferable if you were say updating a time-series and wanted to download just the newest acquisitions for some area. Perhaps there could be a way to specify in calls to download whether to skip, re-download, or error when hitting the same filename.

**Comment by EJFielding** [comment]
I hit this same problem. It would be great if it could not fail but maybe issue a warning and continue.

**Comment by glshort** [comment]
Fix is on its way, for now we'll just skip a download if the file exists, but in the future we'll add some options to validate files via checksums and/or sizes and re-download if they don't match, or to just forcibly re-download no matter what.

In any event, the new approach issues a UserWarning if the file exists but then happily skips the download and carries on. That should be available later today (12/9/21)

**Comment by EJFielding** [comment]
Thanks @glshort. That is a big help.

**Comment by glshort** [comment]
You're welcome, and sorry to @bbuzz31 for the delay!

Going to close this issue, but feel free to reach out if this doesn't get you both where you need to be.

**Comment by bbuzz31** [comment]
> You're welcome, and sorry to @bbuzz31 for the delay!
> 
> Going to close this issue, but feel free to reach out if this doesn't get you both where you need to be.

No problem, thanks a lot!
